DROP TABLE IF EXISTS TRADEDATA;
 
CREATE TABLE TRADEDATA(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  counter_party VARCHAR(250) NOT NULL,
  location VARCHAR(250) NOT NULL,
  commodities VARCHAR(250) DEFAULT NULL,
  market_price INT DEFAULT 0,
  status VARCHAR(250) DEFAULT NULL
);